# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://launchmycareer.github.io
title: LaunchMyCareer Partner Resources
email: launchmycareer@air.org
author: American Institutes for Research
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2017 American Institutes for Research. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/Education_AIR
  - title: github
    url: https://github.com/launchmycareer
  - title: linkedin
    url: https://www.linkedin.com/company-beta/6904/
